#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamersOperzalClient.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SERVICES")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void Insertcamers_operzal_general(camers_operzal_general instance);
    partial void Updatecamers_operzal_general(camers_operzal_general instance);
    partial void Deletecamers_operzal_general(camers_operzal_general instance);
    partial void Insertcamers_operzal_ifns(camers_operzal_ifns instance);
    partial void Updatecamers_operzal_ifns(camers_operzal_ifns instance);
    partial void Deletecamers_operzal_ifns(camers_operzal_ifns instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SERVICESConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<camers_operzal_general> camers_operzal_general
		{
			get
			{
				return this.GetTable<camers_operzal_general>();
			}
		}
		
		public System.Data.Linq.Table<camers_operzal_ifns> camers_operzal_ifns
		{
			get
			{
				return this.GetTable<camers_operzal_ifns>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.camers_operzal_general")]
	public partial class camers_operzal_general : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ifns_code;
		
		private string _camera_img_link;
		
		private string _camera_img_file;
		
		private System.Nullable<int> _camera_disable;
		
		private string _camera_disable_description;
		
		private string _camera_user;
		
		private string _camera_password;
		
		private EntityRef<camers_operzal_ifns> _camers_operzal_ifns;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onifns_codeChanging(string value);
    partial void Onifns_codeChanged();
    partial void Oncamera_img_linkChanging(string value);
    partial void Oncamera_img_linkChanged();
    partial void Oncamera_img_fileChanging(string value);
    partial void Oncamera_img_fileChanged();
    partial void Oncamera_disableChanging(System.Nullable<int> value);
    partial void Oncamera_disableChanged();
    partial void Oncamera_disable_descriptionChanging(string value);
    partial void Oncamera_disable_descriptionChanged();
    partial void Oncamera_userChanging(string value);
    partial void Oncamera_userChanged();
    partial void Oncamera_passwordChanging(string value);
    partial void Oncamera_passwordChanged();
    #endregion
		
		public camers_operzal_general()
		{
			this._camers_operzal_ifns = default(EntityRef<camers_operzal_ifns>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ifns_code", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string ifns_code
		{
			get
			{
				return this._ifns_code;
			}
			set
			{
				if ((this._ifns_code != value))
				{
					if (this._camers_operzal_ifns.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onifns_codeChanging(value);
					this.SendPropertyChanging();
					this._ifns_code = value;
					this.SendPropertyChanged("ifns_code");
					this.Onifns_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_camera_img_link", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string camera_img_link
		{
			get
			{
				return this._camera_img_link;
			}
			set
			{
				if ((this._camera_img_link != value))
				{
					this.Oncamera_img_linkChanging(value);
					this.SendPropertyChanging();
					this._camera_img_link = value;
					this.SendPropertyChanged("camera_img_link");
					this.Oncamera_img_linkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_camera_img_file", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string camera_img_file
		{
			get
			{
				return this._camera_img_file;
			}
			set
			{
				if ((this._camera_img_file != value))
				{
					this.Oncamera_img_fileChanging(value);
					this.SendPropertyChanging();
					this._camera_img_file = value;
					this.SendPropertyChanged("camera_img_file");
					this.Oncamera_img_fileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_camera_disable", DbType="Int")]
		public System.Nullable<int> camera_disable
		{
			get
			{
				return this._camera_disable;
			}
			set
			{
				if ((this._camera_disable != value))
				{
					this.Oncamera_disableChanging(value);
					this.SendPropertyChanging();
					this._camera_disable = value;
					this.SendPropertyChanged("camera_disable");
					this.Oncamera_disableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_camera_disable_description", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string camera_disable_description
		{
			get
			{
				return this._camera_disable_description;
			}
			set
			{
				if ((this._camera_disable_description != value))
				{
					this.Oncamera_disable_descriptionChanging(value);
					this.SendPropertyChanging();
					this._camera_disable_description = value;
					this.SendPropertyChanged("camera_disable_description");
					this.Oncamera_disable_descriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_camera_user", DbType="VarChar(50)")]
		public string camera_user
		{
			get
			{
				return this._camera_user;
			}
			set
			{
				if ((this._camera_user != value))
				{
					this.Oncamera_userChanging(value);
					this.SendPropertyChanging();
					this._camera_user = value;
					this.SendPropertyChanged("camera_user");
					this.Oncamera_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_camera_password", DbType="VarChar(50)")]
		public string camera_password
		{
			get
			{
				return this._camera_password;
			}
			set
			{
				if ((this._camera_password != value))
				{
					this.Oncamera_passwordChanging(value);
					this.SendPropertyChanging();
					this._camera_password = value;
					this.SendPropertyChanged("camera_password");
					this.Oncamera_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="camers_operzal_ifns_camers_operzal_general", Storage="_camers_operzal_ifns", ThisKey="ifns_code", OtherKey="ifns_cod", IsForeignKey=true)]
		public camers_operzal_ifns camers_operzal_ifns
		{
			get
			{
				return this._camers_operzal_ifns.Entity;
			}
			set
			{
				camers_operzal_ifns previousValue = this._camers_operzal_ifns.Entity;
				if (((previousValue != value) 
							|| (this._camers_operzal_ifns.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._camers_operzal_ifns.Entity = null;
						previousValue.camers_operzal_general.Remove(this);
					}
					this._camers_operzal_ifns.Entity = value;
					if ((value != null))
					{
						value.camers_operzal_general.Add(this);
						this._ifns_code = value.ifns_cod;
					}
					else
					{
						this._ifns_code = default(string);
					}
					this.SendPropertyChanged("camers_operzal_ifns");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.camers_operzal_ifns")]
	public partial class camers_operzal_ifns : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ifns_cod;
		
		private string _ifns_name;
		
		private System.Nullable<int> _order;
		
		private EntitySet<camers_operzal_general> _camers_operzal_general;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onifns_codChanging(string value);
    partial void Onifns_codChanged();
    partial void Onifns_nameChanging(string value);
    partial void Onifns_nameChanged();
    partial void OnorderChanging(System.Nullable<int> value);
    partial void OnorderChanged();
    #endregion
		
		public camers_operzal_ifns()
		{
			this._camers_operzal_general = new EntitySet<camers_operzal_general>(new Action<camers_operzal_general>(this.attach_camers_operzal_general), new Action<camers_operzal_general>(this.detach_camers_operzal_general));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ifns_cod", DbType="VarChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ifns_cod
		{
			get
			{
				return this._ifns_cod;
			}
			set
			{
				if ((this._ifns_cod != value))
				{
					this.Onifns_codChanging(value);
					this.SendPropertyChanging();
					this._ifns_cod = value;
					this.SendPropertyChanged("ifns_cod");
					this.Onifns_codChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ifns_name", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string ifns_name
		{
			get
			{
				return this._ifns_name;
			}
			set
			{
				if ((this._ifns_name != value))
				{
					this.Onifns_nameChanging(value);
					this.SendPropertyChanging();
					this._ifns_name = value;
					this.SendPropertyChanged("ifns_name");
					this.Onifns_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[order]", Storage="_order", DbType="Int")]
		public System.Nullable<int> order
		{
			get
			{
				return this._order;
			}
			set
			{
				if ((this._order != value))
				{
					this.OnorderChanging(value);
					this.SendPropertyChanging();
					this._order = value;
					this.SendPropertyChanged("order");
					this.OnorderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="camers_operzal_ifns_camers_operzal_general", Storage="_camers_operzal_general", ThisKey="ifns_cod", OtherKey="ifns_code")]
		public EntitySet<camers_operzal_general> camers_operzal_general
		{
			get
			{
				return this._camers_operzal_general;
			}
			set
			{
				this._camers_operzal_general.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_camers_operzal_general(camers_operzal_general entity)
		{
			this.SendPropertyChanging();
			entity.camers_operzal_ifns = this;
		}
		
		private void detach_camers_operzal_general(camers_operzal_general entity)
		{
			this.SendPropertyChanging();
			entity.camers_operzal_ifns = null;
		}
	}
}
#pragma warning restore 1591
